version: '3'
services:
  influxdb:
    network_mode: "host"
    image: "hypriot/rpi-influxdb"
    ports:
      - "8086:8086"
    volumes: 
      - /var/influxdb:/data
  tefegraf:
    network_mode: "host"
    image: "arm32v7/telegraf"
    # add config file here     
    depends_on:
      - influxdb    
    volumes: 
       - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf 
  grafana:
    image: "fg2it/grafana-armhf:v4.1.2"
    ports: 
      - "3000:3000"
    volumes: 
      - grafana-db:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-conf:/etc/grafana
  chronograf:
    image: chronograf:latest
    volumes:
        # Mount for chronograf database
        - ./chronograf/data/:/var/lib/chronograf/
    ports:
        # The WebUI for Chronograf is served on port 8888
        - "8888:8888"
    depends_on:
        - influxdb
  weather-app:
    image: ruby:2.6     
  speedtest-app:
    image: ruby:2.6    

volumes:
  grafana-db:
    driver: local
  grafana-log:
    driver: local
  grafana-conf:
    driver: local        